// ---- LOGIN ---- //
const FETCHING_LOGIN_DATA = 'FETCHING_LOGIN_DATA'
const FETCHING_LOGIN_DATA_SUCCESS =   'FETCHING_LOGIN_DATA_SUCCESS'
const FETCHING_LOGIN_DATA_FAILURE =   'FETCHING_LOGIN_DATA_FAILURE'

// ---- FEED ---- //
const FETCHING_FEED_DATA = 'FETCHING_FEED_DATA'
const FETCHING_FEED_DATA_SUCCESS = '  FETCHING_FEED_DATA_SUCCESS'
const FETCHING_FEED_DATA_FAILURE = '  FETCHING_FEED_DATA_FAILURE'

// ---- NOTIFICATIONS ---- //
const FETCHING_NOTIFICATION_DATA = 'FETCHING_NOTIFICATION_DATA'
const FETCHING_NOTIFICATION_DATA_SUCCESS = '  FETCHING_NOTIFICATION_DATA_SUCCESS'
const FETCHING_NOTIFICATION_DATA_FAILURE = '  FETCHING_NOTIFICATION_DATA_FAILURE'

const FETCHING_NOTIFICATION_STATUS = 'FETCHING_NOTIFICATION_STATUS'
const FETCHING_NOTIFICATION_STATUS_SUCCESS = '  FETCHING_NOTIFICATION_STATUS_SUCCESS'
const FETCHING_NOTIFICATION_STATUS_FAILURE = '  FETCHING_NOTIFICATION_STATUS_FAILURE'

const FETCHING_MARK_NOTIFICATION_AS_UNSEEN = 'FETCHING_MARK_NOTIFICATION_AS_UNSEEN'
const FETCHING_MARK_NOTIFICATION_AS_UNSEEN_SUCCESS = 'FETCHING_MARK_NOTIFICATION_AS_UNSEEN_SUCCESS'
const FETCHING_MARK_NOTIFICATION_AS_UNSEEN_FAILURE = 'FETCHING_MARK_NOTIFICATION_AS_UNSEEN_FAILURE'


// const NavigateToLogoutScreen = 'NAVIGATE_TO_LOGOUT_SCREEN'; // TODO: Implement logout
// const LOGOUT = 'LOGOUT'

export {
  FETCHING_FEED_DATA, // FEED
  FETCHING_FEED_DATA_SUCCESS,
  FETCHING_FEED_DATA_FAILURE,
  FETCHING_LOGIN_DATA, // LOGIN
  FETCHING_LOGIN_DATA_SUCCESS,
  FETCHING_LOGIN_DATA_FAILURE,
  FETCHING_NOTIFICATION_STATUS, // NOTIFICATION
  FETCHING_NOTIFICATION_STATUS_SUCCESS,
  FETCHING_NOTIFICATION_STATUS_FAILURE,
  FETCHING_NOTIFICATION_DATA, // NOTIFICATION
  FETCHING_NOTIFICATION_DATA_SUCCESS,
  FETCHING_NOTIFICATION_DATA_FAILURE,
  FETCHING_MARK_NOTIFICATION_AS_UNSEEN, // NOTIFICATION
  FETCHING_MARK_NOTIFICATION_AS_UNSEEN_SUCCESS,
  FETCHING_MARK_NOTIFICATION_AS_UNSEEN_FAILURE,
};