// CREATE_ALBUM
const FETCHING_CREATE_ALBUM = 'FETCHING_CREATE_ALBUM'
const FETCHING_CREATE_ALBUM_SUCCESS = 'FETCHING_CREATE_ALBUM_SUCCESS'
const FETCHING_CREATE_ALBUM_FAILURE = 'FETCHING_CREATE_ALBUM_FAILURE'

// ADD_POINT_TO_ALBUM
const FETCHING_ADD_POINT_TO_ALBUM = 'FETCHING_ADD_POINT_TO_ALBUM'
const FETCHING_ADD_POINT_TO_ALBUM_SUCCESS = 'FETCHING_ADD_POINT_TO_ALBUM_SUCCESS'
const FETCHING_ADD_POINT_TO_ALBUM_FAILURE = 'FETCHING_ADD_POINT_TO_ALBUM_FAILURE'

// ADD_USER_TO_ALBUM
const FETCHING_ADD_USER_TO_ALBUM = 'FETCHING_ADD_USER_TO_ALBUM'
const FETCHING_ADD_USER_TO_ALBUM_SUCCESS = 'FETCHING_ADD_USER_TO_ALBUM_SUCCESS'
const FETCHING_ADD_USER_TO_ALBUM_FAILURE = 'FETCHING_ADD_USER_TO_ALBUM_FAILURE'

// GET_ALBUMS_FROM_CURRENT_USER
const FETCHING_GET_ALBUMS_FROM_CURRENT_USER = 'FETCHING_GET_ALBUMS_FROM_CURRENT_USER'
const FETCHING_GET_ALBUMS_FROM_CURRENT_USER_SUCCESS = 'FETCHING_GET_ALBUMS_FROM_CURRENT_USER_SUCCESS'
const FETCHING_GET_ALBUMS_FROM_CURRENT_USER_FAILURE = 'FETCHING_GET_ALBUMS_FROM_CURRENT_USER_FAILURE'

// GET_ALBUMS_FROM_USER
const FETCHING_GET_ALBUMS_FROM_USER = 'FETCHING_GET_ALBUMS_FROM_USER'
const FETCHING_GET_ALBUMS_FROM_USER_SUCCESS = 'FETCHING_GET_ALBUMS_FROM_USER_SUCCESS'
const FETCHING_GET_ALBUMS_FROM_USER_FAILURE = 'FETCHING_GET_ALBUMS_FROM_USER_FAILURE'

// GET_ALBUM_USERS
const FETCHING_GET_ALBUM_USERS = 'FETCHING_GET_ALBUM_USERS'
const FETCHING_GET_ALBUM_USERS_SUCCESS = 'FETCHING_GET_ALBUM_USERS_SUCCESS'
const FETCHING_GET_ALBUM_USERS_FAILURE = 'FETCHING_GET_ALBUM_USERS_FAILURE'

// UPDATE_ALBUM
const FETCHING_UPDATE_ALBUM = 'FETCHING_UPDATE_ALBUM'
const FETCHING_UPDATE_ALBUM_SUCCESS = 'FETCHING_UPDATE_ALBUM_SUCCESS'
const FETCHING_UPDATE_ALBUM_FAILURE = 'FETCHING_UPDATE_ALBUM_FAILURE'

// REMOVE_USER_FROM_ALBUM
const FETCHING_REMOVE_USER_FROM_ALBUM = 'FETCHING_REMOVE_USER_FROM_ALBUM'
const FETCHING_REMOVE_USER_FROM_ALBUM_SUCCESS = 'FETCHING_REMOVE_USER_FROM_ALBUM_SUCCESS'
const FETCHING_REMOVE_USER_FROM_ALBUM_FAILURE = 'FETCHING_REMOVE_USER_FROM_ALBUM_FAILURE'

// DELETE_ALBUM
const FETCHING_DELETE_ALBUM = 'FETCHING_DELETE_ALBUM'
const FETCHING_DELETE_ALBUM_SUCCESS = 'FETCHING_DELETE_ALBUM_SUCCESS'
const FETCHING_DELETE_ALBUM_FAILURE = 'FETCHING_DELETE_ALBUM_FAILURE'

export {
  FETCHING_CREATE_ALBUM,
  FETCHING_CREATE_ALBUM_SUCCESS,
  FETCHING_CREATE_ALBUM_FAILURE,
  FETCHING_ADD_POINT_TO_ALBUM,
  FETCHING_ADD_POINT_TO_ALBUM_SUCCESS,
  FETCHING_ADD_POINT_TO_ALBUM_FAILURE,
  FETCHING_ADD_USER_TO_ALBUM,
  FETCHING_ADD_USER_TO_ALBUM_SUCCESS,
  FETCHING_ADD_USER_TO_ALBUM_FAILURE,
  FETCHING_GET_ALBUMS_FROM_CURRENT_USER,
  FETCHING_GET_ALBUMS_FROM_CURRENT_USER_SUCCESS,
  FETCHING_GET_ALBUMS_FROM_CURRENT_USER_FAILURE,
  FETCHING_GET_ALBUMS_FROM_USER,
  FETCHING_GET_ALBUMS_FROM_USER_SUCCESS,
  FETCHING_GET_ALBUMS_FROM_USER_FAILURE,
  FETCHING_GET_ALBUM_USERS,
  FETCHING_GET_ALBUM_USERS_SUCCESS,
  FETCHING_GET_ALBUM_USERS_FAILURE,
  FETCHING_UPDATE_ALBUM,
  FETCHING_UPDATE_ALBUM_SUCCESS,
  FETCHING_UPDATE_ALBUM_FAILURE,
  FETCHING_REMOVE_USER_FROM_ALBUM,
  FETCHING_REMOVE_USER_FROM_ALBUM_SUCCESS,
  FETCHING_REMOVE_USER_FROM_ALBUM_FAILURE,
  FETCHING_DELETE_ALBUM,
  FETCHING_DELETE_ALBUM_SUCCESS,
  FETCHING_DELETE_ALBUM_FAILURE,
}