const FETCHING_ACCEPT_FRIEND_REQUEST = 'FETCHING_ACCEPT_FRIEND_REQUEST'
const FETCHING_ACCEPT_FRIEND_REQUEST_SUCCESS = 'FETCHING_ACCEPT_FRIEND_REQUEST_SUCCESS'
const FETCHING_ACCEPT_FRIEND_REQUEST_FAILURE = 'FETCHING_ACCEPT_FRIEND_REQUEST_FAILURE'

const FETCHING_DECLINE_FRIEND_REQUEST = 'FETCHING_DECLINE_FRIEND_REQUEST'
const FETCHING_DECLINE_FRIEND_REQUEST_SUCCESS = 'FETCHING_DECLINE_FRIEND_REQUEST_SUCCESS'
const FETCHING_DECLINE_FRIEND_REQUEST_FAILURE = 'FETCHING_DECLINE_FRIEND_REQUEST_FAILURE'

const FETCHING_FRIENDS = 'FETCHING_FRIENDS'
const FETCHING_FRIENDS_SUCCESS = 'FETCHING_FRIENDS_SUCCESS'
const FETCHING_FRIENDS_FAILURE = 'FETCHING_FRIENDS_FAILURE'

const SEND_FRIEND_REQUEST = 'SEND_FRIEND_REQUEST'
const SEND_FRIEND_REQUEST_SUCCESS = 'SEND_FRIEND_REQUEST_SUCCESS'
const SEND_FRIEND_REQUEST_FAILURE = 'SEND_FRIEND_REQUEST_FAILURE'

const DELETING_FRIEND = 'DELETING_FRIEND'
const DELETE_FRIEND_SUCCESS = 'DELETE_FRIEND_SUCCESS'
const DELETE_FRIEND_FAILURE = 'DELETE_FRIEND_FAILURE'

export {
  FETCHING_ACCEPT_FRIEND_REQUEST,
  FETCHING_ACCEPT_FRIEND_REQUEST_SUCCESS,
  FETCHING_ACCEPT_FRIEND_REQUEST_FAILURE,
  FETCHING_DECLINE_FRIEND_REQUEST,
  FETCHING_DECLINE_FRIEND_REQUEST_SUCCESS,
  FETCHING_DECLINE_FRIEND_REQUEST_FAILURE,
  FETCHING_FRIENDS,
  FETCHING_FRIENDS_SUCCESS,
  FETCHING_FRIENDS_FAILURE,
  SEND_FRIEND_REQUEST,
  SEND_FRIEND_REQUEST_SUCCESS,
  SEND_FRIEND_REQUEST_FAILURE,
  DELETING_FRIEND,
  DELETE_FRIEND_SUCCESS,
  DELETE_FRIEND_FAILURE,
}