const FETCHING_SEARCH = 'FETCHING_SEARCH'
const FETCHING_SEARCH_SUCCESS = 'FETCHING_SEARCH_SUCCESS'
const FETCHING_SEARCH_FAILURE = 'FETCHING_SEARCH_FAILURE'

export {
  FETCHING_SEARCH,
  FETCHING_SEARCH_SUCCESS,
  FETCHING_SEARCH_FAILURE,
}