const FETCHING_USER = 'FETCHING_USER'
const FETCHING_USER_SUCCESS = 'FETCHING_USER_SUCCESS'
const FETCHING_USER_FAILURE = 'FETCHING_USER_FAILURE'

const FETCHING_OTHER_USER = 'FETCHING_OTHER_USER'
const FETCHING_OTHER_USER_SUCCESS = 'FETCHING_OTHER_USER_SUCCESS'
const FETCHING_OTHER_USER_FAILURE = 'FETCHING_OTHER_USER_FAILURE'

export {
  FETCHING_USER,
  FETCHING_USER_SUCCESS,
  FETCHING_USER_FAILURE,
  FETCHING_OTHER_USER,
  FETCHING_OTHER_USER_SUCCESS,
  FETCHING_OTHER_USER_FAILURE,
}